/*
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EdtlUiModule extends AbstractEdtlUiModule {

	public EdtlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
