/*
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import su.nsk.iae.edtl.EdtlRuntimeModule;
import su.nsk.iae.edtl.EdtlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EdtlIdeSetup extends EdtlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EdtlRuntimeModule(), new EdtlIdeModule()));
	}
	
}
