/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.edtl.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.edtl.edtl.EdtlPackage;
import su.nsk.iae.edtl.edtl.XorExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XorExpressionImpl extends ExpressionImpl implements XorExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XorExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EdtlPackage.Literals.XOR_EXPRESSION;
  }

} //XorExpressionImpl
