/*
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EdtlStandaloneSetup extends EdtlStandaloneSetupGenerated {

	public static void doSetup() {
		new EdtlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
