/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.edtl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abbr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.edtl.edtl.Abbr#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getAbbr()
 * @model
 * @generated
 */
public interface Abbr extends CrossVarAbbr
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getAbbr_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.Abbr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // Abbr
