/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.edtl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.edtl.edtl.CompExpression#getCompOp <em>Comp Op</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getCompExpression()
 * @model
 * @generated
 */
public interface CompExpression extends AndExpression
{
  /**
   * Returns the value of the '<em><b>Comp Op</b></em>' attribute.
   * The literals are from the enumeration {@link su.nsk.iae.edtl.edtl.CompOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp Op</em>' attribute.
   * @see su.nsk.iae.edtl.edtl.CompOperator
   * @see #setCompOp(CompOperator)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getCompExpression_CompOp()
   * @model
   * @generated
   */
  CompOperator getCompOp();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.CompExpression#getCompOp <em>Comp Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp Op</em>' attribute.
   * @see su.nsk.iae.edtl.edtl.CompOperator
   * @see #getCompOp()
   * @generated
   */
  void setCompOp(CompOperator value);

} // CompExpression
