/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.edtl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getConstant <em>Constant</em>}</li>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getTau <em>Tau</em>}</li>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getV <em>V</em>}</li>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getMacros <em>Macros</em>}</li>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getArgs <em>Args</em>}</li>
 *   <li>{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getNestExpr <em>Nest Expr</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression()
 * @model
 * @generated
 */
public interface PrimaryExpression extends UnExpression
{
  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(String)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_Constant()
   * @model
   * @generated
   */
  String getConstant();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #getConstant()
   * @generated
   */
  void setConstant(String value);

  /**
   * Returns the value of the '<em><b>Tau</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tau</em>' containment reference.
   * @see #setTau(TauExpression)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_Tau()
   * @model containment="true"
   * @generated
   */
  TauExpression getTau();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getTau <em>Tau</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tau</em>' containment reference.
   * @see #getTau()
   * @generated
   */
  void setTau(TauExpression value);

  /**
   * Returns the value of the '<em><b>V</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' reference.
   * @see #setV(CrossVarAbbr)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_V()
   * @model
   * @generated
   */
  CrossVarAbbr getV();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getV <em>V</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' reference.
   * @see #getV()
   * @generated
   */
  void setV(CrossVarAbbr value);

  /**
   * Returns the value of the '<em><b>Macros</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Macros</em>' reference.
   * @see #setMacros(Macros)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_Macros()
   * @model
   * @generated
   */
  Macros getMacros();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getMacros <em>Macros</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Macros</em>' reference.
   * @see #getMacros()
   * @generated
   */
  void setMacros(Macros value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(ParamAssignmentElements)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_Args()
   * @model containment="true"
   * @generated
   */
  ParamAssignmentElements getArgs();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(ParamAssignmentElements value);

  /**
   * Returns the value of the '<em><b>Nest Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nest Expr</em>' containment reference.
   * @see #setNestExpr(Expression)
   * @see su.nsk.iae.edtl.edtl.EdtlPackage#getPrimaryExpression_NestExpr()
   * @model containment="true"
   * @generated
   */
  Expression getNestExpr();

  /**
   * Sets the value of the '{@link su.nsk.iae.edtl.edtl.PrimaryExpression#getNestExpr <em>Nest Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nest Expr</em>' containment reference.
   * @see #getNestExpr()
   * @generated
   */
  void setNestExpr(Expression value);

} // PrimaryExpression
