/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.edtl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.edtl.edtl.EdtlPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends CrossVarAbbr
{
} // Variable
