/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class BoolTerm implements PrimaryTerm {
  public boolean value;

  public BoolTerm(final boolean value) {
    this.value = value;
  }

  public BoolTerm(final BoolTerm term) {
    this.value = term.value;
  }

  @Override
  public BoolTerm copy() {
    return new BoolTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    BoolTerm that = ((BoolTerm) o);
    return java.util.Objects.equals(Boolean.valueOf(this.value), Boolean.valueOf(that.value));
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
