/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class FeTerm implements UnaryTerm {
  public Term term;

  public FeTerm(final Term term) {
    this.term = term;
  }

  public FeTerm(final FeTerm feTerm) {
    Term _xifexpression = null;
    if ((feTerm.term != null)) {
      _xifexpression = feTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public FeTerm copy() {
    return new FeTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    FeTerm that = ((FeTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
