/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class FTerm implements Term {
  public Term term;

  public FTerm(final Term term) {
    this.term = term;
  }

  public FTerm(final FTerm fTerm) {
    Term _xifexpression = null;
    if ((fTerm.term != null)) {
      _xifexpression = fTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public FTerm copy() {
    return new FTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    FTerm that = ((FTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
