/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class GTerm implements Term {
  public Term term;

  public GTerm(final Term term) {
    this.term = term;
  }

  public GTerm(final GTerm gTerm) {
    Term _xifexpression = null;
    if ((gTerm.term != null)) {
      _xifexpression = gTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public GTerm copy() {
    return new GTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    GTerm that = ((GTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
