/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class HighTerm implements UnaryTerm {
  public Term term;

  public HighTerm(final Term term) {
    this.term = term;
  }

  public HighTerm(final HighTerm highTerm) {
    Term _xifexpression = null;
    if ((highTerm.term != null)) {
      _xifexpression = highTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public HighTerm copy() {
    return new HighTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    HighTerm that = ((HighTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
