/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class ReTerm implements UnaryTerm {
  public Term term;

  public ReTerm(final Term term) {
    this.term = term;
  }

  public ReTerm(final ReTerm reTerm) {
    Term _xifexpression = null;
    if ((reTerm.term != null)) {
      _xifexpression = reTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public ReTerm copy() {
    return new ReTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    ReTerm that = ((ReTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
