/**
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.generator;

import com.google.common.base.Objects;

@SuppressWarnings("all")
public class WTerm implements Term {
  public Term term;

  public WTerm(final Term term) {
    this.term = term;
  }

  public WTerm(final WTerm wTerm) {
    Term _xifexpression = null;
    if ((wTerm.term != null)) {
      _xifexpression = wTerm.term.copy();
    } else {
      _xifexpression = null;
    }
    this.term = _xifexpression;
  }

  @Override
  public WTerm copy() {
    return new WTerm(this);
  }

  @Override
  public boolean equals(final Object o) {
    if ((this == o)) {
      return true;
    }
    if (((o == null) || (!Objects.equal(this.getClass(), o.getClass())))) {
      return false;
    }
    WTerm that = ((WTerm) o);
    return java.util.Objects.equals(this.term, that.term);
  }

  @Override
  public int hashCode() {
    return 1;
  }
}
