/*
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEdtlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(su.nsk.iae.edtl.edtl.EdtlPackage.eINSTANCE);
		return result;
	}
}
