/*
 * generated by Xtext 2.34.0
 */
package su.nsk.iae.edtl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import su.nsk.iae.edtl.ui.internal.EdtlActivator;

public class EdtlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EdtlActivator.getInstance().getInjector("su.nsk.iae.edtl.Edtl");
	}

}
